# Generated by Django 4.2.4 on 2023-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ верификации'),
        ),
    ]
