# Generated by Django 4.2.4 on 2023-08-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_date',
        ),
    ]
